
version: '3.8'

services:
  riot-producer:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: riot-producer
    env_file:
      - .env
    depends_on:
      - kafka
    networks:
      - app-tier 
    restart: always

  riot-consumer:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: riot-consumer
    env_file:
      - .env
    networks:
      - app-tier
    restart: always

  kafka:
    image: 'bitnami/kafka:latest'
    env_file:
      - .env
    networks:
      - app-tier
    restart: always

  mongo:
    image: mongo
    env_file:
      - .env
    networks:
      - app-tier
    volumes:
      - mongo_data:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      ME_CONFIG_BASICAUTH: "false"
    networks:
      - app-tier
    restart: always

volumes:
  mongo_data:

networks:
  app-tier:
    driver: bridge


 
